### ISSUE TITLE
AWS: handle rate limits errors when fetching secrets

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-universal#5]
**Description**
A rate limit error while fetching the parameters should either:

- abort the function with a 500 
- or wait and retry later

```
2021-04-14T09:01:36.298Z	7a3a96f0-350b-435a-8f04-5923ebfe4972	ERROR	unable to get parameters ThrottlingException: Rate exceeded
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ThrottlingException',
  time: 2021-04-14T09:01:36.297Z,
  requestId: '0014473a-2458-445e-a5f7-3ddca2dff603',
  statusCode: 400,
  retryable: true
}
```

**Comment by trieloff** [comment]
I'd abort with a 429, which the upstream is able to handle.
